"""Add address plate requests

Revision ID: 0eaf319d7b3c
Revises: f1c43aa099e9
Create Date: 2026-09-22 11:55:26.825395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eaf319d7b3c'
down_revision: Union[str, Sequence[str], None] = 'f1c43aa099e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address_plate_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_address_plate_requests_property_id'), 'address_plate_requests', ['property_id'], unique=False)
    op.create_index(op.f('ix_address_plate_requests_requested_by'), 'address_plate_requests', ['requested_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_address_plate_requests_requested_by'), table_name='address_plate_requests')
    op.drop_index(op.f('ix_address_plate_requests_property_id'), table_name='address_plate_requests')
    op.drop_table('address_plate_requests')
    # ### end Alembic commands ###
