"""Add installation assignments

Revision ID: 1bd5872c23ae
Revises: 7cadfe89a42e
Create Date: 2026-09-28 14:47:01.851768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bd5872c23ae'
down_revision: Union[str, Sequence[str], None] = '7cadfe89a42e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('installation_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('plate_id', sa.Uuid(), nullable=False),
    sa.Column('contractor_id', sa.Uuid(), nullable=False),
    sa.Column('contractor_member_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_by', sa.Uuid(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('assigned', 'in_progress', 'submitted', 'completed', 'cancelled')", name='ck_installation_assignment_status'),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ),
    sa.ForeignKeyConstraint(['contractor_member_id'], ['contractor_members.id'], ),
    sa.ForeignKeyConstraint(['plate_id'], ['address_plates.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installation_assignments_assigned_by'), 'installation_assignments', ['assigned_by'], unique=False)
    op.create_index(op.f('ix_installation_assignments_contractor_id'), 'installation_assignments', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_installation_assignments_contractor_member_id'), 'installation_assignments', ['contractor_member_id'], unique=False)
    op.create_index(op.f('ix_installation_assignments_plate_id'), 'installation_assignments', ['plate_id'], unique=False)
    op.create_index(op.f('ix_installation_assignments_property_id'), 'installation_assignments', ['property_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_installation_assignments_property_id'), table_name='installation_assignments')
    op.drop_index(op.f('ix_installation_assignments_plate_id'), table_name='installation_assignments')
    op.drop_index(op.f('ix_installation_assignments_contractor_member_id'), table_name='installation_assignments')
    op.drop_index(op.f('ix_installation_assignments_contractor_id'), table_name='installation_assignments')
    op.drop_index(op.f('ix_installation_assignments_assigned_by'), table_name='installation_assignments')
    op.drop_table('installation_assignments')
    # ### end Alembic commands ###
