"""Add property installation verification records

Revision ID: 4fbedbea3c9b
Revises: e3adcb9faaae
Create Date: 2026-09-23 18:26:30.501157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fbedbea3c9b'
down_revision: Union[str, Sequence[str], None] = 'e3adcb9faaae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_installation_verifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('installation_id', sa.Uuid(), nullable=False),
    sa.Column('verified_by', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['installation_id'], ['property_installations.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_installation_verifications_installation_id'), 'property_installation_verifications', ['installation_id'], unique=False)
    op.create_index(op.f('ix_property_installation_verifications_verified_by'), 'property_installation_verifications', ['verified_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_property_installation_verifications_verified_by'), table_name='property_installation_verifications')
    op.drop_index(op.f('ix_property_installation_verifications_installation_id'), table_name='property_installation_verifications')
    op.drop_table('property_installation_verifications')
    # ### end Alembic commands ###
