"""add address plate manufacturing orders

Revision ID: 579671213aba
Revises: 0eaf319d7b3c
Create Date: 2026-09-22 20:52:25.706119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '579671213aba'
down_revision: Union[str, Sequence[str], None] = '0eaf319d7b3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manufacturing_orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_code', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manufacturing_orders_approved_by'), 'manufacturing_orders', ['approved_by'], unique=False)
    op.create_index(op.f('ix_manufacturing_orders_created_by'), 'manufacturing_orders', ['created_by'], unique=False)
    op.create_index(op.f('ix_manufacturing_orders_order_code'), 'manufacturing_orders', ['order_code'], unique=True)
    op.create_index(op.f('ix_manufacturing_orders_status'), 'manufacturing_orders', ['status'], unique=False)
    op.add_column('address_plates', sa.Column('manufacturing_order_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_address_plates_manufacturing_order_id'), 'address_plates', ['manufacturing_order_id'], unique=False)
    op.create_foreign_key('fk_address_plates_manufacturing_order_id', 'address_plates', 'manufacturing_orders', ['manufacturing_order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_address_plates_manufacturing_order_id', 'address_plates', type_='foreignkey')
    op.drop_index(op.f('ix_address_plates_manufacturing_order_id'), table_name='address_plates')
    op.drop_column('address_plates', 'manufacturing_order_id')
    op.drop_index(op.f('ix_manufacturing_orders_status'), table_name='manufacturing_orders')
    op.drop_index(op.f('ix_manufacturing_orders_order_code'), table_name='manufacturing_orders')
    op.drop_index(op.f('ix_manufacturing_orders_created_by'), table_name='manufacturing_orders')
    op.drop_index(op.f('ix_manufacturing_orders_approved_by'), table_name='manufacturing_orders')
    op.drop_table('manufacturing_orders')
    # ### end Alembic commands ###
