"""add installation assignment cancellation fields

Revision ID: 59761e2a54ef
Revises: 8961964a0bfd
Create Date: 2026-09-29 00:24:48.118129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59761e2a54ef'
down_revision: Union[str, Sequence[str], None] = '8961964a0bfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('installation_assignments', sa.Column('cancelled_by', sa.Uuid(), nullable=True))
    op.add_column('installation_assignments', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('installation_assignments', sa.Column('cancellation_reason', sa.Text(), nullable=True))
    op.create_index(op.f('ix_installation_assignments_cancelled_by'), 'installation_assignments', ['cancelled_by'], unique=False)
    op.create_foreign_key('fk_installation_assignments_cancelled_by_users', 'installation_assignments', 'users', ['cancelled_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_installation_assignments_cancelled_by_users', 'installation_assignments', type_='foreignkey')
    op.drop_index(op.f('ix_installation_assignments_cancelled_by'), table_name='installation_assignments')
    op.drop_column('installation_assignments', 'cancellation_reason')
    op.drop_column('installation_assignments', 'cancelled_at')
    op.drop_column('installation_assignments', 'cancelled_by')
    # ### end Alembic commands ###
