"""Add property verification records

Revision ID: 6f17d6c0ef39
Revises: 71faaec089ba
Create Date: 2026-09-21 14:44:27.885222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f17d6c0ef39'
down_revision: Union[str, Sequence[str], None] = '71faaec089ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_verifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('verified_by', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_verifications_property_id'), 'property_verifications', ['property_id'], unique=False)
    op.create_index(op.f('ix_property_verifications_verified_by'), 'property_verifications', ['verified_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_property_verifications_verified_by'), table_name='property_verifications')
    op.drop_index(op.f('ix_property_verifications_property_id'), table_name='property_verifications')
    op.drop_table('property_verifications')
    # ### end Alembic commands ###
