"""Add employee clearance to users

Revision ID: 71faaec089ba
Revises: d4236fad8548
Create Date: 2026-09-21 12:18:15.528175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71faaec089ba'
down_revision: Union[str, Sequence[str], None] = 'd4236fad8548'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('clearance', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'clearance')
    # ### end Alembic commands ###
