"""Add property spaces

Revision ID: 8cfb0dbd300f
Revises: 585effde6a8a
Create Date: 2026-09-24 18:23:04.959441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cfb0dbd300f'
down_revision: Union[str, Sequence[str], None] = '585effde6a8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spaces',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('floor_id', sa.Uuid(), nullable=False),
    sa.Column('space_number', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('space_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('floor_id', 'space_number', name='uq_space_floor_number')
    )
    op.create_index(op.f('ix_spaces_floor_id'), 'spaces', ['floor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spaces_floor_id'), table_name='spaces')
    op.drop_table('spaces')
    # ### end Alembic commands ###
