"""Add property access authorization

Revision ID: b8108b340abc
Revises: 6f17d6c0ef39
Create Date: 2026-09-21 19:05:13.970774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8108b340abc'
down_revision: Union[str, Sequence[str], None] = '6f17d6c0ef39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_access',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('access_type', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'property_id', 'access_type', name='uq_property_access_user_property_type')
    )
    op.create_index(op.f('ix_property_access_property_id'), 'property_access', ['property_id'], unique=False)
    op.create_index(op.f('ix_property_access_user_id'), 'property_access', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_property_access_user_id'), table_name='property_access')
    op.drop_index(op.f('ix_property_access_property_id'), table_name='property_access')
    op.drop_table('property_access')
    # ### end Alembic commands ###
