"""Remove location fields from property addresses

Revision ID: b9a26722c383
Revises: 1e35d3f1062e
Create Date: 2026-09-30 21:47:36.820567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'b9a26722c383'
down_revision: Union[str, Sequence[str], None] = '1e35d3f1062e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_property_addresses_location'), table_name='property_addresses', postgresql_using='gist')
    op.drop_column('property_addresses', 'location')
    op.drop_column('property_addresses', 'latitude')
    op.drop_column('property_addresses', 'longitude')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_addresses', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('property_addresses', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('property_addresses', sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_property_addresses_location'), 'property_addresses', ['location'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###
