"""add marketplace listings

Revision ID: c8e99868c180
Revises: 2499f1e16422
Create Date: 2026-09-30 12:32:37.245645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8e99868c180'
down_revision: Union[str, Sequence[str], None] = '2499f1e16422'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=True),
    sa.Column('floor_id', sa.Uuid(), nullable=True),
    sa.Column('space_id', sa.Uuid(), nullable=True),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'published', 'unpublished')", name='ck_listings_status'),
    sa.CheckConstraint("transaction_type IN ('sale', 'rent')", name='ck_listings_transaction_type'),
    sa.CheckConstraint('\n            (\n                (property_id IS NOT NULL)::integer +\n                (floor_id IS NOT NULL)::integer +\n                (space_id IS NOT NULL)::integer\n            ) = 1\n            ', name='ck_listings_exactly_one_target'),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listings_floor_id'), 'listings', ['floor_id'], unique=False)
    op.create_index(op.f('ix_listings_property_id'), 'listings', ['property_id'], unique=False)
    op.create_index(op.f('ix_listings_space_id'), 'listings', ['space_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listings_space_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_property_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_floor_id'), table_name='listings')
    op.drop_table('listings')
    # ### end Alembic commands ###
