"""Add dispatch tables

Revision ID: cb988e5510c6
Revises: 579671213aba
Create Date: 2026-09-23 00:55:35.776347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb988e5510c6'
down_revision: Union[str, Sequence[str], None] = '579671213aba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispatches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dispatch_code', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('recipient_name', sa.String(length=255), nullable=False),
    sa.Column('recipient_phone', sa.String(length=50), nullable=False),
    sa.Column('tracking_reference', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatches_created_by'), 'dispatches', ['created_by'], unique=False)
    op.create_index(op.f('ix_dispatches_dispatch_code'), 'dispatches', ['dispatch_code'], unique=True)
    op.create_index(op.f('ix_dispatches_status'), 'dispatches', ['status'], unique=False)
    op.create_index(op.f('ix_dispatches_tracking_reference'), 'dispatches', ['tracking_reference'], unique=False)
    op.create_table('dispatch_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dispatch_id', sa.Uuid(), nullable=False),
    sa.Column('plate_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dispatch_id'], ['dispatches.id'], ),
    sa.ForeignKeyConstraint(['plate_id'], ['address_plates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatch_items_dispatch_id'), 'dispatch_items', ['dispatch_id'], unique=False)
    op.create_index(op.f('ix_dispatch_items_plate_id'), 'dispatch_items', ['plate_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dispatch_items_plate_id'), table_name='dispatch_items')
    op.drop_index(op.f('ix_dispatch_items_dispatch_id'), table_name='dispatch_items')
    op.drop_table('dispatch_items')
    op.drop_index(op.f('ix_dispatches_tracking_reference'), table_name='dispatches')
    op.drop_index(op.f('ix_dispatches_status'), table_name='dispatches')
    op.drop_index(op.f('ix_dispatches_dispatch_code'), table_name='dispatches')
    op.drop_index(op.f('ix_dispatches_created_by'), table_name='dispatches')
    op.drop_table('dispatches')
    # ### end Alembic commands ###
