"""add property installations

Revision ID: e3adcb9faaae
Revises: 7d5025d4c209
Create Date: 2026-09-23 14:57:53.799850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3adcb9faaae'
down_revision: Union[str, Sequence[str], None] = '7d5025d4c209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_installations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('plate_id', sa.Uuid(), nullable=False),
    sa.Column('installer_id', sa.Uuid(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('accuracy_meters', sa.Float(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['installer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['plate_id'], ['address_plates.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_installations_installer_id'), 'property_installations', ['installer_id'], unique=False)
    op.create_index(op.f('ix_property_installations_plate_id'), 'property_installations', ['plate_id'], unique=False)
    op.create_index(op.f('ix_property_installations_property_id'), 'property_installations', ['property_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_property_installations_property_id'), table_name='property_installations')
    op.drop_index(op.f('ix_property_installations_plate_id'), table_name='property_installations')
    op.drop_index(op.f('ix_property_installations_installer_id'), table_name='property_installations')
    op.drop_table('property_installations')
    # ### end Alembic commands ###
