"""Add address plate lifecycle events

Revision ID: f1c43aa099e9
Revises: b8108b340abc
Create Date: 2026-09-22 10:48:52.021203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1c43aa099e9'
down_revision: Union[str, Sequence[str], None] = 'b8108b340abc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address_plate_lifecycle_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plate_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('performed_by', sa.Uuid(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['plate_id'], ['address_plates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_address_plate_lifecycle_events_event_type'), 'address_plate_lifecycle_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_address_plate_lifecycle_events_performed_by'), 'address_plate_lifecycle_events', ['performed_by'], unique=False)
    op.create_index(op.f('ix_address_plate_lifecycle_events_plate_id'), 'address_plate_lifecycle_events', ['plate_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_address_plate_lifecycle_events_plate_id'), table_name='address_plate_lifecycle_events')
    op.drop_index(op.f('ix_address_plate_lifecycle_events_performed_by'), table_name='address_plate_lifecycle_events')
    op.drop_index(op.f('ix_address_plate_lifecycle_events_event_type'), table_name='address_plate_lifecycle_events')
    op.drop_table('address_plate_lifecycle_events')
    # ### end Alembic commands ###
